var annotated_dup =
[
    [ "Edge", "class_edge.html", "class_edge" ],
    [ "EdgeList", "class_edge_list.html", "class_edge_list" ],
    [ "Face_io", "struct_face__io.html", "struct_face__io" ],
    [ "icMatrix2x2", "classic_matrix2x2.html", "classic_matrix2x2" ],
    [ "icMatrix3x3", "classic_matrix3x3.html", "classic_matrix3x3" ],
    [ "icVector2", "classic_vector2.html", "classic_vector2" ],
    [ "icVector3", "classic_vector3.html", "classic_vector3" ],
    [ "neighbor", "structneighbor.html", "structneighbor" ],
    [ "node", "structnode.html", "structnode" ],
    [ "node_main", "structnode__main.html", "structnode__main" ],
    [ "OtherData", "struct_other_data.html", "struct_other_data" ],
    [ "OtherElem", "struct_other_elem.html", "struct_other_elem" ],
    [ "PlyElement", "struct_ply_element.html", "struct_ply_element" ],
    [ "PlyFile", "struct_ply_file.html", "struct_ply_file" ],
    [ "PlyOtherElems", "struct_ply_other_elems.html", "struct_ply_other_elems" ],
    [ "PlyOtherProp", "struct_ply_other_prop.html", "struct_ply_other_prop" ],
    [ "PlyProperty", "struct_ply_property.html", "struct_ply_property" ],
    [ "PlyPropRules", "struct_ply_prop_rules.html", "struct_ply_prop_rules" ],
    [ "PlyRuleList", "struct_ply_rule_list.html", "struct_ply_rule_list" ],
    [ "Polyhedron", "class_polyhedron.html", "class_polyhedron" ],
    [ "RuleName", "struct_rule_name.html", "struct_rule_name" ],
    [ "segment", "structsegment.html", "structsegment" ],
    [ "streamlet", "structstreamlet.html", "structstreamlet" ],
    [ "Triangle", "class_triangle.html", "class_triangle" ],
    [ "TriangleList", "class_triangle_list.html", "class_triangle_list" ],
    [ "Vertex", "class_vertex.html", "class_vertex" ],
    [ "Vertex_io", "struct_vertex__io.html", "struct_vertex__io" ],
    [ "VertexList", "class_vertex_list.html", "class_vertex_list" ]
];